### ISSUE TITLE
bingo配置

### ISSUE THREAD

**Issue by Lai-pishe** [FAS-Server/FAS-bingo#5]
安照说明配置的config但不知道哪里出来问题，希望大佬可以帮忙看看问题，Python使用的是3.8.9 MCDR使用的是2.3.3，文件夹都是直接复制粘贴的，Python使用的是3.8.9 MCDR使用的是2.3.3下面的图片是config中我修改过的地方-图1、2，发现mcdr log文件夹里的log内容好少，就不上传文件了附上一张图片-图3
![image](https://user-images.githubusercontent.com/105760140/168938945-a8a4a7e2-8711-4b40-8ee0-65eb027760ad.png)
![image](https://user-images.githubusercontent.com/105760140/168937766-40d3dd45-1488-4f83-a6ad-90ab0767b074.png)
![image](https://user-images.githubusercontent.com/105760140/168943276-36003306-065a-494d-b8d2-09f2058eee64.png)
启动后会出现第4图以及后面图片的内容，图4后面还有红色的字，就是吧在-handle.bingo_handler.BingoHandler里的字符都输出了一遍
![image](https://user-images.githubusercontent.com/105760140/168943515-878d2a77-c6bd-447a-a1a5-bafee1cde816.png)

![image](https://user-images.githubusercontent.com/105760140/168944032-72875aee-aa80-4d19-87ca-f0c74d6c6492.png)

![image](https://user-images.githubusercontent.com/105760140/168943695-b32a9964-72f4-433d-9d68-323e915d26ef.png)
![image](https://user-images.githubusercontent.com/105760140/168943802-2abc301f-5c67-4fec-9033-e192e8b23ebc.png)
![image](https://user-images.githubusercontent.com/105760140/168943867-2ccdfa89-a3f4-433f-bd46-b101786ce6e3.png)

**Comment by 401U** [comment]
`custom_handlers`配置写法的格式有误
正确用例如下
```yaml
custom_handlers:
- a.b.c.handler
```
注意`-`后面的空格
[MCDR文档](https://mcdreforged.readthedocs.io/zh_CN/latest/configure.html#custom-handlers=)中也有对此配置的说明

**Comment by Lai-pishe** [comment]
您好，非常感谢您的回信，但我不得不在打扰一下您，按照您的说明已经解决了这个问题并且进入了游戏，但不知道为什么MCDR变成了乱码，是我哪里又配置出问题了吗
![image](https://user-images.githubusercontent.com/105760140/168975520-5487ae34-d3b8-4d04-988d-6807579bb9a5.png)
然后还是有显示这些
![image](https://user-images.githubusercontent.com/105760140/168976043-cad0d38c-fddd-4b10-a08b-11c5414abfed.png)
![image](https://user-images.githubusercontent.com/105760140/168976178-a5c0f033-a4c0-4054-88ff-6b5b10651ed4.png)
![image](https://user-images.githubusercontent.com/105760140/168976318-c61ba635-3865-4e2d-bfbd-85e6bf4bdfa3.png)

**Comment by 401U** [comment]
这是编码问题，按需修改encoding和decoding即可

**Comment by Lai-pishe** [comment]
虽然很不好意思，但我又一次遇到问题了，我以为是op的问题，所以给自己了op但还是不行
![image](https://user-images.githubusercontent.com/105760140/168998056-6e993601-7324-430d-b6e8-4e79d116e6e1.png)

**Comment by 401U** [comment]
paper插件装了吗？如果确定安装了可以试着手动发送`/all !!bg`或者`!!bg`看看会是什么情况
另外最好来点发送命令或者点击文本后给的日志信息方便定位错误

**Comment by Lai-pishe** [comment]
非常感谢您的提醒，我看了一下，发现自己只装了一个jar文件，没有下载item_data，已经可以成功运行了，但我又遇到了一个问题，他不显示图像，是我bingo插件哪里出问题了吗，游戏和插件都是18.1版的
![image](https://user-images.githubusercontent.com/105760140/169198484-24cf0bf2-b775-4b63-bb45-e11ea1138ad8.png)
![image](https://user-images.githubusercontent.com/105760140/169199347-79085eaf-adba-4b16-ac9c-bdcf9e4bbbce.png)

**Comment by 401U** [comment]
报错信息显示为 找不到相应的图片，请确保图片数据是解压出来的(而不是压缩包)

**Comment by Lai-pishe** [comment]
az，这波属实是小丑行为了，压缩包里压缩包我属实是没想到，最后两个问题，因为不知道服务器加了数据包会有什么变化，我用单人试了一下数据包显示数据包验证失败，如果还是使用这个数据包会显示   ，是我数据包没下最新的吗，还是我哪里没配置，游戏版本18.1
![image](https://user-images.githubusercontent.com/105760140/169313355-ae4df6c4-fdd3-4030-88da-5db581d20e71.png)
游戏进行完点重启会重启失败，然后界面也直接崩没了是需要加服务器自启的插件吗
![image](https://user-images.githubusercontent.com/105760140/169315181-bbd49226-89ca-46e0-b0ce-7859f50fb583.png)

**Comment by 401U** [comment]
数据包有版本限制，现在这个大概是给1.16用的，高版本可以不用数据包（因为只是提供了缩小群系尺寸的功能）
